### ISSUE TITLE
mako fails with 3.8.0b2 on Windows

### ISSUE THREAD

**Issue by lazka** [python/pyperformance#63] opened 2019-07-23 17:16 UTC
```python
INFO:root:Running `C:\Python38\venv\cpython3.8-2459c2ec2c3d\Scripts\python.exe -u C:\Python38\venv\cpython3.8-2459c2ec2c3d\lib\site-packages\pyperformance\benchmarks\bm_mako.py --output C:\Users\xy\AppData\Local\Temp\tmpdezyn81_`
Traceback (most recent call last):
  File "C:\Python38\venv\cpython3.8-2459c2ec2c3d\lib\site-packages\pyperformance\benchmarks\bm_mako.py", line 20, in <module>
    from mako.template import Template   # noqa
  File "C:\Python38\venv\cpython3.8-2459c2ec2c3d\lib\site-packages\mako\template.py", line 10, in <module>
    from mako.lexer import Lexer
  File "C:\Python38\venv\cpython3.8-2459c2ec2c3d\lib\site-packages\mako\lexer.py", line 11, in <module>
    from mako import parsetree, exceptions, compat
  File "C:\Python38\venv\cpython3.8-2459c2ec2c3d\lib\site-packages\mako\parsetree.py", line 9, in <module>
    from mako import exceptions, ast, util, filters, compat
  File "C:\Python38\venv\cpython3.8-2459c2ec2c3d\lib\site-packages\mako\exceptions.py", line 11, in <module>
    from mako import util, compat
  File "C:\Python38\venv\cpython3.8-2459c2ec2c3d\lib\site-packages\mako\util.py", line 11, in <module>
    from mako import compat
  File "C:\Python38\venv\cpython3.8-2459c2ec2c3d\lib\site-packages\mako\compat.py", line 123, in <module>
    time_func = time.clock
AttributeError: module 'time' has no attribute 'clock'
ERROR: Benchmark mako failed: Benchmark died
```

**Comment by lazka** [comment] 2019-07-23 20:49
Still in upstream master, needs fixing..

**Comment by lazka** [comment] 2019-07-23 21:35
I've filed https://github.com/sqlalchemy/mako/issues/301

**Comment by vstinner** [comment] 2019-07-29 13:15
Fixed in just releaesd pyperformance 0.9.1 by commit d631ab36e7a07f8a7f17591a922df39818cb724e. Thanks for the bug report and thanks for reporting the issue to sqlalchemy!

**Comment by lazka** [comment] 2019-07-29 18:47
I think this should be reopened. There is no mako release including the fix yet.

**Comment by vstinner** [comment] 2019-07-29 22:28
mako benchmark works for me with Python version: 3.8.0b2+ (64-bit) revision 36fd7b6f01. Maybe Python has been modified to fix the Mako issue, I don't know. Python 3.8 beta 3 has just been released ;-)

**Comment by lazka** [comment] 2019-07-30 06:01
It's a Windows only bug.

**Comment by vstinner** [comment] 2019-07-30 09:23
> It's a Windows only bug.

If you want to support Windows, I would prefer to have a Windows CI, otherwise regressions are likely to appear again.

**Comment by lazka** [comment] 2019-07-30 12:34
I'll look into CI. Do you prefer appveyor or azure?

**Comment by vstinner** [comment] 2019-07-30 12:35
Whatever works :-)

**Comment by lazka** [comment] 2019-07-30 21:32
I've opened a PR -> #70 (azure because it's faster)

**Closed** 2019-08-12 11:07 UTC
